spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/airing_db
spring.datasource.username=postgres
spring.datasource.password=hyeong0374
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
